package com.model;

import javax.ws.rs.FormParam;

import com.comm.util.BaseForm;

public class CustomerUnite extends BaseForm {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer_unite.id
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
	@FormParam("id")
    private Long id;
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer_unite.customer_id
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
	@FormParam("customerId")
    private Long customerId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer_unite.nickname
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
	@FormParam("nickname")
    private String nickname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer_unite.mobile
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
	@FormParam("mobile")
    private String mobile;
	
	@FormParam("uniteTimeMobile")
    private String uniteTimeMobile;
	

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer_unite.email
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
	@FormParam("email")
    private String email;
	
	@FormParam("uniteTimeEmail")
    private String uniteTimeEmail;
	

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer_unite.unite_id_qq
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
	@FormParam("uniteIdQq")
    private Integer uniteIdQq;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer_unite.unite_name_qq
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
	@FormParam("uniteNameQq")
    private String uniteNameQq;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer_unite.unite_flag_qq
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
	@FormParam("uniteFlagQq")
    private Integer uniteFlagQq;
	
	@FormParam("uniteTimeQq")
    private String uniteTimeQq;
	
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer_unite.unite_id_sina
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
	@FormParam("uniteIdSina")
    private Integer uniteIdSina;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer_unite.unite_name_sina
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
	@FormParam("uniteNameSina")
    private String uniteNameSina;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer_unite.unite_flag_sina
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
	@FormParam("uniteFlagSina")
    private Integer uniteFlagSina;
	
	@FormParam("uniteTimeSina")
    private String uniteTimeSina;
	

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer_unite.unite_id_baidu
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
	@FormParam("uniteIdBaidu")
    private Integer uniteIdBaidu;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer_unite.unite_name_baidu
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
	@FormParam("uniteNameBaidu")
    private String uniteNameBaidu;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer_unite.unite_flag_baidu
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
	@FormParam("uniteFlagBaidu")
    private Integer uniteFlagBaidu;

	@FormParam("uniteTimeBaidu")
    private String uniteTimeBaidu;
	
	@FormParam("uniteIdWeixin")
    private Integer uniteIdWeixin;
	
	@FormParam("uniteNameWeixin")
    private String uniteNameWeixin;
	
	@FormParam("uniteFlagWeixin")
    private Integer uniteFlagWeixin;
	
	@FormParam("uniteTimeWeixin")
    private String uniteTimeWeixin;
	
	@FormParam("uniteIdCaos")
    private Integer uniteIdCaos;
	
	@FormParam("uniteNameCaos")
    private String uniteNameCaos;
	
	@FormParam("uniteFlagCaos")
    private Integer uniteFlagCaos;
	
	@FormParam("uniteTimeCaos")
    private String uniteTimeCaos;
	
	@FormParam("createTime")
	private String createTime;
	
	
    public String getCreateTime() {
		return createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer_unite.passwd
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
	@FormParam("passwd")
    private String passwd;
	
	
	@FormParam("isValid")
	private Integer isValid;
	
	private Integer isCheckEmail;
	
	private Integer isCheckMobile;
	
	private Integer customerRole;
	
	private String checkEmailTime;
	private String checkMobileTime;
	
	private String uniteNameZhgk;
	
	private String uniteTimeZhgk;
	
	private String initPasswd;
	
	@FormParam("sendSiteId")
	private Integer sendSiteId;
	
	private String areasExpertise;//为了导出excel 的时候可以查询到该条数据 by xp 2016年11月29日
	
	
	public String getAreasExpertise() {
		return areasExpertise;
	}

	public void setAreasExpertise(String areasExpertise) {
		this.areasExpertise = areasExpertise;
	}

	public Integer getSendSiteId() {
		return sendSiteId;
	}

	public void setSendSiteId(Integer sendSiteId) {
		this.sendSiteId = sendSiteId;
	}

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer_unite.id
     *
     * @return the value of customer_unite.id
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer_unite.id
     *
     * @param id the value for customer_unite.id
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer_unite.customer_id
     *
     * @return the value of customer_unite.customer_id
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer_unite.customer_id
     *
     * @param customerId the value for customer_unite.customer_id
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer_unite.nickname
     *
     * @return the value of customer_unite.nickname
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer_unite.nickname
     *
     * @param nickname the value for customer_unite.nickname
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer_unite.mobile
     *
     * @return the value of customer_unite.mobile
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer_unite.mobile
     *
     * @param mTele the value for customer_unite.mobile
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    public String getUniteTimeMobile() {
        return uniteTimeMobile;
    }
    public void setUniteTimeMobile(String uniteTimeMobile) {
        this.uniteTimeMobile = uniteTimeMobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer_unite.e_mail
     *
     * @return the value of customer_unite.e_mail
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer_unite.email
     *
     * @param eMail the value for customer_unite.email
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }
    
    public String getUniteTimeEmail() {
        return uniteTimeEmail;
    }
    public void setUniteTimeEmail(String uniteTimeEmail) {
        this.uniteTimeEmail = uniteTimeEmail;
    }

    
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer_unite.unite_id_qq
     *
     * @return the value of customer_unite.unite_id_qq
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public Integer getUniteIdQq() {
        return uniteIdQq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer_unite.unite_id_qq
     *
     * @param uniteIdQq the value for customer_unite.unite_id_qq
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public void setUniteIdQq(Integer uniteIdQq) {
        this.uniteIdQq = uniteIdQq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer_unite.unite_name_qq
     *
     * @return the value of customer_unite.unite_name_qq
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public String getUniteNameQq() {
        return uniteNameQq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer_unite.unite_name_qq
     *
     * @param uniteNameQq the value for customer_unite.unite_name_qq
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public void setUniteNameQq(String uniteNameQq) {
        this.uniteNameQq = uniteNameQq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer_unite.unite_flag_qq
     *
     * @return the value of customer_unite.unite_flag_qq
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public Integer getUniteFlagQq() {
        return uniteFlagQq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer_unite.unite_flag_qq
     *
     * @param uniteFlagQq the value for customer_unite.unite_flag_qq
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public void setUniteFlagQq(Integer uniteFlagQq) {
        this.uniteFlagQq = uniteFlagQq;
    }
    
    public String getUniteTimeQq() {
        return uniteTimeQq;
    }
    public void setUniteTimeQq(String uniteTimeQq) {
        this.uniteTimeQq = uniteTimeQq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer_unite.unite_id_sina
     *
     * @return the value of customer_unite.unite_id_sina
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public Integer getUniteIdSina() {
        return uniteIdSina;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer_unite.unite_id_sina
     *
     * @param uniteIdSina the value for customer_unite.unite_id_sina
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public void setUniteIdSina(Integer uniteIdSina) {
        this.uniteIdSina = uniteIdSina;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer_unite.unite_name_sina
     *
     * @return the value of customer_unite.unite_name_sina
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public String getUniteNameSina() {
        return uniteNameSina;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer_unite.unite_name_sina
     *
     * @param uniteNameSina the value for customer_unite.unite_name_sina
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public void setUniteNameSina(String uniteNameSina) {
        this.uniteNameSina = uniteNameSina;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer_unite.unite_flag_sina
     *
     * @return the value of customer_unite.unite_flag_sina
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public Integer getUniteFlagSina() {
        return uniteFlagSina;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer_unite.unite_flag_sina
     *
     * @param uniteFlagSina the value for customer_unite.unite_flag_sina
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public void setUniteFlagSina(Integer uniteFlagSina) {
        this.uniteFlagSina = uniteFlagSina;
    }
    
    public String getUniteTimeSina() {
        return uniteTimeSina;
    }
    public void setUniteTimeSina(String uniteTimeSina) {
        this.uniteTimeSina = uniteTimeSina;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer_unite.unite_id_baidu
     *
     * @return the value of customer_unite.unite_id_baidu
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public Integer getUniteIdBaidu() {
        return uniteIdBaidu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer_unite.unite_id_baidu
     *
     * @param uniteIdBaidu the value for customer_unite.unite_id_baidu
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public void setUniteIdBaidu(Integer uniteIdBaidu) {
        this.uniteIdBaidu = uniteIdBaidu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer_unite.unite_name_baidu
     *
     * @return the value of customer_unite.unite_name_baidu
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public String getUniteNameBaidu() {
        return uniteNameBaidu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer_unite.unite_name_baidu
     *
     * @param uniteNameBaidu the value for customer_unite.unite_name_baidu
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public void setUniteNameBaidu(String uniteNameBaidu) {
        this.uniteNameBaidu = uniteNameBaidu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer_unite.unite_flag_baidu
     *
     * @return the value of customer_unite.unite_flag_baidu
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public Integer getUniteFlagBaidu() {
        return uniteFlagBaidu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer_unite.unite_flag_baidu
     *
     * @param uniteFlagBaidu the value for customer_unite.unite_flag_baidu
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public void setUniteFlagBaidu(Integer uniteFlagBaidu) {
        this.uniteFlagBaidu = uniteFlagBaidu;
    }
    
    public String getUniteTimeBaidu() {
        return uniteTimeBaidu;
    }
    public void setUniteTimeBaidu(String uniteTimeBaidu) {
        this.uniteTimeBaidu = uniteTimeBaidu;
    }
    
    public Integer getUniteIdWeixin() {
        return uniteIdWeixin;
    }
    public void setUniteIdWeixin(Integer uniteIdWeixin) {
        this.uniteIdWeixin = uniteIdWeixin;
    }

    public String getUniteNameWeixin() {
        return uniteNameWeixin;
    }
    public void setUniteNameWeixin(String uniteNameWeixin) {
        this.uniteNameWeixin = uniteNameWeixin;
    }
	
	public Integer getUniteFlagWeixin() {
        return uniteFlagWeixin;
    }
    public void setUniteFlagWeixin(Integer uniteFlagWeixin) {
        this.uniteFlagWeixin = uniteFlagWeixin;
    }
	
	public String getUniteTimeWeixin() {
        return uniteTimeWeixin;
    }
    public void setUniteTimeWeixin(String uniteTimeWeixin) {
        this.uniteTimeWeixin = uniteTimeWeixin;
    }
    
    
    
    
    
    public Integer getUniteIdCaos() {
        return uniteIdCaos;
    }
    public void setUniteIdCaos(Integer uniteIdCaos) {
        this.uniteIdCaos = uniteIdCaos;
    }

    public String getUniteNameCaos() {
        return uniteNameCaos;
    }
    public void setUniteNameCaos(String uniteNameCaos) {
        this.uniteNameCaos = uniteNameCaos;
    }
	
	public Integer getUniteFlagCaos() {
        return uniteFlagCaos;
    }
    public void setUniteFlagCaos(Integer uniteFlagCaos) {
        this.uniteFlagCaos = uniteFlagCaos;
    }
	
	public String getUniteTimeCaos() {
        return uniteTimeCaos;
    }
    public void setUniteTimeCaos(String uniteTimeCaos) {
        this.uniteTimeCaos = uniteTimeCaos;
    }
    
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer_unite.passwd
     *
     * @return the value of customer_unite.passwd
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer_unite.passwd
     *
     * @param passwd the value for customer_unite.passwd
     *
     * @abatorgenerated Tue Feb 11 10:26:09 CST 2014
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
    
    public Integer getIsValid() {
        return isValid;
    }
    
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
    
    public Integer getIsCheckEmail() {
        return isCheckEmail;
    }
    
    public void setIsCheckEmail(Integer isCheckEmail) {
        this.isCheckEmail = isCheckEmail;
    }
    
    public Integer getIsCheckMobile() {
        return isCheckMobile;
    }
    
    public void setIsCheckMobile(Integer isCheckMobile) {
        this.isCheckMobile = isCheckMobile;
    }
    
    public Integer getCustomerRole() {
        return customerRole;
    }
    
    public void setCustomerRole(Integer customerRole) {
        this.customerRole = customerRole;
    }
    
    
    public String getCheckEmailTime() {
        return checkEmailTime;
    }

    public void setCheckEmailTime(String checkEmailTime) {
        this.checkEmailTime = checkEmailTime;
    }
    
    public String getCheckMobileTime() {
        return checkMobileTime;
    }

    public void setCheckMobileTime(String checkMobileTime) {
        this.checkMobileTime = checkMobileTime;
    }
    
    public String getUniteNameZhgk() {
        return uniteNameZhgk;
    }

    public void setUniteNameZhgk(String uniteNameZhgk) {
        this.uniteNameZhgk = uniteNameZhgk;
    }
	
    public String getUniteTimeZhgk() {
        return uniteTimeZhgk;
    }

    public void setUniteTimeZhgk(String uniteTimeZhgk) {
        this.uniteTimeZhgk = uniteTimeZhgk;
    }
    
    public String getInitPasswd() {
        return initPasswd;
    }

    public void setInitPasswd(String initPasswd) {
        this.initPasswd = initPasswd;
    }

}